# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20190327_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.NullBooleanField(default=False),
        ),
    ]
