# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_profile_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='upload_date',
            new_name='pub_date',
        ),
    ]
