# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20190327_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='pub_date',
            new_name='upload_date',
        ),
    ]
